# Generated by Django 2.0.5 on 2018-06-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0003_auto_20180606_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=1000)),
            ],
        ),
    ]
