# Generated by Django 2.0.5 on 2018-06-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0006_adminlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='postquery',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
