# Generated by Django 2.0.5 on 2018-06-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0008_employeelogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='postquery',
            name='id1',
            field=models.IntegerField(null=True),
        ),
    ]
