# Generated by Django 2.0.5 on 2018-06-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0009_postquery_id1'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='suggestion',
            field=models.TextField(null=True),
        ),
    ]
