# Generated by Django 2.0.5 on 2018-06-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0010_contact_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='postquery',
            name='id1',
        ),
    ]
