# Generated by Django 2.0.5 on 2018-06-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0011_auto_20180608_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='postquery',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
