# Generated by Django 2.0.5 on 2018-06-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0012_auto_20180608_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.TextField(null=True)),
                ('query', models.TextField()),
                ('answer', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminAnswer',
        ),
        migrations.DeleteModel(
            name='EmpAnswer',
        ),
        migrations.DeleteModel(
            name='KnowStatus',
        ),
        migrations.DeleteModel(
            name='PostQuery',
        ),
        migrations.AddField(
            model_name='contact',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employeelogin',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
